### ISSUE TITLE
Some users cannot hear eachother due to IPv6 not beeing supported.

### ISSUE THREAD

**Issue by stogoh** [ottomated/CrewLink-server#103]
**Symptoms**
Some players cannot hear eachother.

**Cause**
If some players do not have IPv6 enabled or is not supported they could not head the other players.

**Solution**
Disable IPv6 in the local computer's settings.

**Comment by OiYouYeahYou** [comment]
I'm expecting this is a `won't fix` because the app is using chromium's upstream implementation.
