### ISSUE TITLE
How to set the ADDRESS environment variable. on linux ubuntu server 20.04

### ISSUE THREAD

**Issue by tompointexe** [ottomated/CrewLink-server#125]
Hi, i have the "You must set the ADDRESS environment variable." error, after trying all thge methods i've seen in the issues it wont work ... if you could help me on this part and make it more clear in the readme ?? thanks

**Comment by tompointexe** [comment]
NVM ... Fixed it myself

**Comment by iqfx** [comment]
If anyone is struggling with this aswell, checkout: #132
