### ISSUE TITLE
Yarn <error> You must set the ADDRESS environment variable.

### ISSUE THREAD

**Issue by Playmoon** [ottomated/CrewLink-server#127]
Ive tried doing various things like adding -e ADDRESS="..." or adding a config in the file with the adress, but nothing seems to work and it keeps telling me the same error, can anyone please tell me how I start this Server, without it giving me this ERROR, thanks!

**Comment by Playmoon** [comment]
Like I said in the Title, the Issue is for Yarn, or when you do the manual Installation. This is a Workaround for Haroku, wich sadly doesnt fix the Manual Installation

**Comment by Cahllagerfeld** [comment]
I dont know how adding dependencies is handled for contributing here, but would adding the dotenv-package and adding ADDRESS there be a thing?

**Comment by d1m3b4g** [comment]
Getting the same problem in a docker image too. Didn't have the issue when I pulled an image to a different machine about 3 weeks ago so something has changed in a newer drop. Unsure what to do as I don't really want anything in the Docker image to persist. Any ideas?

**Comment by Cahllagerfeld** [comment]
If starting with docker u can read instructions in #117. 
I dont know how adding dependencies is handled in contribution here, but when starting via node, adding the dotenv-package might be a thing.

**Comment by CMeyers326496** [comment]
I used `ADDRESS='[my-ip]' yarn start` to set the node env variable before running the start command.

**Comment by Playmoon** [comment]
> 
> 
> I used `ADDRESS='[my-ip]' yarn start` to set the node env variable before running the start command.

If i try that it tells me that i either wrote it incorrectly, or the command couldnt be found

**Comment by CMeyers326496** [comment]
> > I used `ADDRESS='[my-ip]' yarn start` to set the node env variable before running the start command.
> 
> If i try that it tells me that i either wrote it incorrectly, or the command couldnt be found

I am running the command in git bash on a windows server after executing the previous steps in the readme to install node and yarn. if your environment is different the fix may be different for you, not sure

**Comment by Playmoon** [comment]
> I am running the command in git bash on a windows server after executing the previous steps in the readme to install node and yarn. if your environment is different the fix may be different for you, not sure

Ah! Now it works, didnt know you were using git bash, but now it works perfectly fine, thanks! 👍
