### ISSUE TITLE
Yarn manual installation error

### ISSUE THREAD

**Issue by Kimochii-x3** [ottomated/CrewLink-server#132]
I'm not very good when it comes to github, I've followed the guide for manual yarn installation. At the end when I do 'yarn start' I receive the error: <error> You must set the ADDRESS environment variable. That is not clear to me how to do on the readme file. When I try to google an installation process, its all videos about docker that are 15-20 minutes long, I do not wish to install docker, nor use heroku. What can be done about this?

**Comment by iqfx** [comment]
From my understanding of yarn (which is not much).
You need to create a `process.env` file inside of the cloned repository.

Inside of this file you would simply just declare the variables like this:

```
PORT=443
ADDRESS=192.168.1.69
NAME=CrewLink-Server
HTTPS=true
SSLPATH=/etc/letsencrypt/live/mydomain.com/
```

A server without a SSL certificate would look like this:
```
ADDRESS=192.168.1.69
NAME=CrewLink-Server
```

**Comment by Kimochii-x3** [comment]
I tried what you suggested just now, I still receive that error, both ways with SSL and without SSL.

**Comment by iqfx** [comment]
Turns out we have to define our environment variables in a different way that I'm not used to.
However I did manage to get it working by renaming the process.env file to just .env
Then running 

`yarn add dotenv`

Followed by adding this line of code to src/index.ts right below line 8.

`require('dotenv').config();`

Hope that helps.

**Comment by Kimochii-x3** [comment]
Thank you, this process worked and the server appears to have started. Now I only have to figure out as to why it doesn't connect when I change the IP (which is a different problem, I'll be closing this issue).
