### ISSUE TITLE
the Docker container closes immediately

### ISSUE THREAD

**Issue by Nelllow** [ottomated/CrewLink-server#138]
There is my problem (I'm a beginner) :

C:\Users\XXX>docker run -d -p 9736:9736 ottomated/crewlink-server:latest
39513bace2fe1a06dee0e712f60fb500cd160fb94625a19b60137ed2dccd6b00

C:\Users\XXX>docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

C:\Users\XXX>docker ps -a
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS                     PORTS     NAMES
39513bace2fe   ottomated/crewlink-server:latest   "docker-entrypoint.s…"   7 seconds ago   Exited (1) 6 seconds ago             trusting_goldberg

I tried some solutions found on the web but none of them work

**Comment by beautivile** [comment]
You need to have the required environment variable otherwise it will not start: ADDRESS.

docker run -d -p 9736:9736 -e http:YOURDOMAIN.TLD:9736 ottomated/crewlink-server:latest

Also you can see what was happening in the container logs by the following:
docker logs --follow trusting_goldberg

**Comment by EvanMorr** [comment]
Hello

**Comment by Nelllow** [comment]
Thanks for answer @beautivile. I'm a beginner so what do you mean by "your domain" ?

**Comment by h0vdev** [comment]
Hi, you need to use the correct command:

docker run -d -p 9736:9736 -e ADDRESS=http://DOMAIN.domain:9736 ottomated/crewlink-server:latest

**Comment by Nelllow** [comment]
Sorry for the delay of response. Thanks, it work now !
