### ISSUE TITLE
Docker Image Size

### ISSUE THREAD

**Issue by jhechtf** [ottomated/CrewLink-server#141]
We should probably have an alpine image so minimize the size of the docker file.

I created a rough image simply using alpine as the base and got the following size differences:

![Alpine image size: 270MB; default image size 1.1GB](https://user-images.githubusercontent.com/8152471/103817205-11ecc200-501b-11eb-861f-73828a61f303.png)

Taking the image from 1.1GB to 270MB is an approximately 75% reduction in size.

**Comment by OiYouYeahYou** [comment]
fixed in: https://github.com/ottomated/CrewLink-server/pull/98

**Comment by jhechtf** [comment]
Closing Ticket
