### ISSUE TITLE
Srv record for crewlink

### ISSUE THREAD

**Issue by tompointexe** [ottomated/CrewLink-server#143]
Hi, my domain & server is behind cloudflare, what do i do to make a srv record for it ? thanks

**Comment by billyjbryant** [comment]
You should just be able to make an A or cname record that directs to your server's public IP.  The client has to support SRV for an SRV record to be of any use. To make a new record, you would need the hostname or IP address that your application is deployed to then add this in as a new DNS record in CloudFlare.

**Comment by tompointexe** [comment]
ok thanks :)
