### ISSUE TITLE
Client fails to connect to server behind reverse ssl proxy. 

### ISSUE THREAD

**Issue by sifotes** [ottomated/CrewLink-server#15]
Server accessible at https://crewlink.mydomain.tld
Client gives the following error on both http and https
![image](https://user-images.githubusercontent.com/26532668/101230734-06e9ef00-3675-11eb-8053-4aa94302a983.png)
Server running from latest docker image - ottomated/crewlink-server latest 1334cfe753c7

**Comment by KMcNickel** [comment]
I imagine that you have up-to-date certificates set up on the server (if you don't... fix that)
Also I notice that the URL in the dialog only has one slash after "https:"
What reverse proxy are you using and can you post the configuration and any logs from it that pertain to this?

**Comment by sifotes** [comment]
Doh, it was indeed the typo you pointed out. All is working now, thank you for included https support.
