### ISSUE TITLE
[Suggestion] Docker auto update

### ISSUE THREAD

**Issue by Brandonv101** [ottomated/CrewLink-server#158]
Hi there,

There should be a feature that allows the docker image to auto update as the address environment variable needs to be reset to the hosted IP each time a new docker image needs to be pulled.

Thanks!

**Comment by jhechtf** [comment]
to clarify, are you talking about whenever a new version of the crewlink server comes out that your docker image should auto-update?

**Comment by Brandonv101** [comment]
Yes that is what I am referring to since currently a new docker image needs to be pulled and then the address environment variable needs to be updated to the public IP.

**Comment by Zedifuu** [comment]
update.sh
```
git pull origin master
docker-compose down 
docker-compose up -d --build
```

For now, Maybe? 
and just keep an eye on updates?
Can remove -d to monitor rebuild if you want.

**Comment by Brandonv101** [comment]
Thanks I think that will work fine for now

**Comment by OiYouYeahYou** [comment]
If it's resolved, maybe you should close it :)

**Comment by Brandonv101** [comment]
Sorry forgot to close the ticket with my last comment
