### ISSUE TITLE
i cant clone the repo

### ISSUE THREAD

**Issue by mnaouares** [ottomated/CrewLink-server#161]
![image_2021-01-22_221757](https://user-images.githubusercontent.com/28548721/105548243-adf71880-5cff-11eb-97be-4e1e0e877835.png)

**Comment by wwsean08** [comment]
Looks like you need to either install git, or if it is installed, add it to the PATH so it's easily accessible via the command line.

**Comment by mnaouares** [comment]
> Looks like you need to either install git, or if it is installed, add it to the PATH so it's easily accessible via the command line.

okey tnx bro gona ty that rn
