### ISSUE TITLE
Manual Installation yarn dont start

### ISSUE THREAD

**Issue by mnaouares** [ottomated/CrewLink-server#163]
![image](https://user-images.githubusercontent.com/28548721/105552073-bb160680-5d03-11eb-999e-b0380e3f4c2f.png)

**Comment by wwsean08** [comment]
you need to `cd` into the directory that was created when you cloned the repo (crewlink-server most likely) first, then run yarn start.  Assuming it's that you'd run `cd crewlink-server` then `yarn install` and finally `yarn start` per the readme

**Comment by mnaouares** [comment]
> you need to `cd` into the directory that was created when you cloned the repo (crewlink-server most likely) first, then run yarn start. Assuming it's that you'd run `cd crewlink-server` then `yarn install` and finally `yarn start` per the readme

ty bro for so much
