### ISSUE TITLE
Among us update 2020.12.05

### ISSUE THREAD

**Issue by lakomyt** [ottomated/CrewLink-server#20]
There was an update... i think a few minutes ago and crewlink doesn't work saying that i have unspupported among version.

**Comment by Doherty98** [comment]
Same, just gonna have to wait a bit until the mod is updated.

**Comment by natemckn** [comment]
Using new offset data from here, it isn't too hard to update the server to support the new 2020.12.05 version:  
https://github.com/denverquane/amonguscapture/commit/65af78f55a6c218c561d6aca895f72f4bd0e5c5f  

I'm too lazy to make a pull request, but I already updated my docker server image by doing these steps:

```
docker exec -u 0 -it <dockerimagename> bash
cd offsets
cp 2020.12.3.yml 2020.12.5.yml
sed -i 's/0x193C154/0x1BE1074/g' 2020.12.5.yml
sed -i 's/0x193C054/0x1BE0BB8/g' 2020.12.5.yml
sed -i 's/0x193BA9C/0x1BE0CB4/g' 2020.12.5.yml
sed -i 's/0x193C018/0x1BE10BC/g' 2020.12.5.yml
sed -i 's/0x1858970/0x1B5AB00/g' 2020.12.5.yml
```

**Comment by klemek** [comment]
@natemckn I had the same idea but unfortunately it doesn't work.
Crewlink starts but fails to capture the game state (ex: in a room, it says "menu" but displays player skin, and no audio is working)

**Comment by lakomyt** [comment]
thanks! @natemckn it works :))

**Comment by baltland** [comment]
> Using new offset data from here, it isn't too hard to update the server to support the new 2020.12.05 version:
> [denverquane/amonguscapture@65af78f](https://github.com/denverquane/amonguscapture/commit/65af78f55a6c218c561d6aca895f72f4bd0e5c5f)
> 
> I'm too lazy to make a pull request, but I already updated my docker server image by doing these steps:
> 
> ```
> docker exec -u 0 -it <dockerimagename> bash
> cd offsets
> cp 2020.12.3.yml 2020.12.5.yml
> sed -i 's/0x193C154/0x1BE1074/g' 2020.12.5.yml
> sed -i 's/0x193C054/0x1BE0BB8/g' 2020.12.5.yml
> sed -i 's/0x193BA9C/0x1BE0CB4/g' 2020.12.5.yml
> sed -i 's/0x193C018/0x1BE10BC/g' 2020.12.5.yml
> sed -i 's/0x1858970/0x1B5AB00/g' 2020.12.5.yml
> ```

I have the same issue but i am new to this site and dont know jack sh*t about coding what does this mean and how do I update crewlink

**Comment by lakomyt** [comment]
if you are in this repository it means that you have your private server, right?

**Comment by Dont4getm3** [comment]
i am not a programmer. how does one fix it?

**Comment by BubbleCast** [comment]
I am a dum dum, so could really use an explanation of how to fix it myself if possible :)
