### ISSUE TITLE
Automated private server creation

### ISSUE THREAD

**Issue by TheRaven81** [ottomated/CrewLink-server#4]
possibly make a binary to use, to make creation of a private server easier for those who are not so technically inclined?

**Comment by notchloeno** [comment]
This seems pretty unnecessary, the process is pretty simply

**Comment by FireMasterK** [comment]
Just use docker.

**Comment by TheRaven81** [comment]
"Simple" is subjective. And Docker is reported to be insecure, so I don't trust it.
