### ISSUE TITLE
NGINX SSL Offloading - Users can't join actual crew

### ISSUE THREAD

**Issue by Phelms215** [ottomated/CrewLink-server#42]
Not sure what information you would need to effectively troubleshoot this - can provide a dev server if needed though. 

Installed CrewLink docker image with standard port. Running NGINX with a valid SSL on port 443. The website loads fine however when users connect to the game they are never entered into the lobby within the app and the connected user count never increases.

Tried proxy to both the IP below directly and 127.0.0.1 - preferably the latter so I can only bind port 9736 on localhost (forcing the proxy to be required). 

Site: https://crewlink.networkglitch.com/
http://172.93.101.11:9736

**NGINX Config**
```
server {

server_name  crewlink.networkglitch.com;
access_log /var/log/nginx/crewlink.access.log;
error_log /var/log/nginx/crewlink.error.log;

#ssl_protocols       TLSv1.2 TLSv1.3;
#ssl_ciphers         HIGH:!aNULL:!MD5;
#ssl_certificate /etc/nginx/ssl/crewlink.networkglitch.com.crt;
#ssl_certificate_key /etc/nginx/ssl/crewlink.networkglitch.key;

location / {
   proxy_pass http://127.0.0.1:9736;
}

listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/crewlink.networkglitch.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/crewlink.networkglitch.com/privkey.pem; # managed by Certbot
include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Comment by sotif** [comment]
Here is what you want to do:
```
location / {
   proxy_pass http://localhost:9736;
   proxy_http_version 1.1;
   proxy-set_header Upgrade $http_upgrade;
   proxy_set_header Connection "upgrade";
   proxy_read_timeout 86400;
}
```
And maybe also listen to port 80 and redirect requests to 443.

**Comment by Phelms215** [comment]
Confirmed that fixed it
