### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Oof-ram** [ottomated/CrewLink-server#43]
So I was trying to play among us with proximity chat with my friends earlier today.
So I installed crewlink because I saw a article about it then when i try to use it it gives me this error

"Please use another voice server. https://crewl.ink gave this error: Request failed with status code 502.
![image](https://user-images.githubusercontent.com/75710858/101568600-b54ca780-3987-11eb-9b9e-5fd3f639a40f.png)

Restart the app after you fix this"
and also in the menu thing it says this
"Error
Make sure that the Voice Server is correct in the settings and you are using the latest version of Among Us. If there was a recent update, CrewLink might not work for a few days."
![image](https://user-images.githubusercontent.com/75710858/101568794-268c5a80-3988-11eb-9569-fa3c0e4c826e.png)

So can someone please give me some help with this and thanks in advance :D
(edit) i am using CrewLink v1.1.5 btw

**Comment by ReportCardsMC** [comment]
This is because crewl.ink is offline rn, you can use https://github.com/ottomated/CrewLink-server to make your own server

**Comment by xPolar** [comment]
You can also use any of the servers that aren't down on the [Crewlink status page](https://status.crewl.ink/)!

**Comment by Oof-ram** [comment]
Thanks ill look in to making my own server @ReportCardsMC 
and thanks for the status page @xPolar
