### ISSUE TITLE
Running crewlink on raspberry pi

### ISSUE THREAD

**Issue by Endur3D** [ottomated/CrewLink-server#45]
I can't get the docker container to work, it exits or keeps restarting as soon as I create one.

I've used the "quick way" with docker run.

**Comment by steeven-tronet** [comment]
> I can't get the do

Have you solved the problem ?
Because I'm trying to start CrewLink on RPI with docker it is not working : exit code 1

```
standard_init_linux.go:219: exec user process caused: exec format error
standard_init_linux.go:219: exec user process caused: exec format error
```
