### ISSUE TITLE
[Suggestion] Server-Client based server option instead of p2p

### ISSUE THREAD

**Issue by Kheiral** [ottomated/CrewLink-server#5]
I'm under the impression right now that the server's current setup is p2p which can cause numerous issues.

I've had times where P1 can only hear P2 and P2 is the only person who can hear P1. P3, 4, 5, 6, etc. are totally left out of P1's conversation but can still talk to P2 just fine. I know this is an issue on its own but there's a few other things

As it stands the fact that the connection is p2p causes a significant security risk to those concerned about their IP getting leaked assuming they don't have a VPN.

With it being P2P it also means that if the server gets shut down, people can still talk to each other which is just not supposed to happen I would think.

Lastly, with the use of a dedicated server, you could opt to use a better voice codec for people who have computers powerful enough to handle that kind of server being run.

**Comment by ottomated** [comment]
You're looking for a TURN server. The amount of CPU usage this would require in this repo is prohibitive, and therefore I'm closing this issue.
