### ISSUE TITLE
Connection issues for other users

### ISSUE THREAD

**Issue by strikerthedj** [ottomated/CrewLink-server#57]
Hi,

Im running the server on a Heroku deployment and users in my group are having issues with connections. Often time, some cant hear others but can here others. Essentially everyone is not on the same page and some people have hearing issues despite their settings being correct. Is this a Heroku thing? If so, what solutions are available?

**Comment by JRHB314** [comment]
I've been having the same issue. Our strategy that we've worked out temporarily:

1. Before every game in lobby, check to make sure you can hear everyone.
2. If you can't, go to the top wall while you close and reopen CrewLink, unless someone else is already reopening. For some reason multiple people simultaneously reopening makes it worse.
3. If someone else is already reopening, wait by the chairs in a line.
4. Once you can HEAR everyone, go to the right wall to indicate that.
5. When everyone is on the right wall, you know that everyone can hear everyone and should start the game.
