### ISSUE TITLE
Can't setup reverse proxy

### ISSUE THREAD

**Issue by preciel** [ottomated/CrewLink-server#6]
Because URL is always easier to remember than IP, I'm trying to set up a vhost for crewlink.
But for one reason or another, it seems like CrewLink (1.1.2) will not works with Apache reverse proxy.

This is my current vhost, did I do something wrong ?

```
<VirtualHost *:80>
    ServerName my-crewlink.com

    Redirect / https://my-crewlink.com/
</VirtualHost>

<IfModule mod_ssl.c>
<VirtualHost _default_:443>
    ServerName my-crewlink.com

    DirectoryIndex disabled

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} =websocket [NC]
    RewriteRule /(.*)           ws://127.0.0.1:20098/$1 [P,L]
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*)           http://127.0.0.1:20098/$1 [P,L]

    ProxyPass / http://127.0.0.1:20098/
    ProxyPassReverse / http://127.0.0.1:20098/
    ProxyRequests Off

    SSLCertificateFile /etc/letsencrypt/live/my-crewlink.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/my-crewlink.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

    ErrorLog /var/www/my-crewlink.com/log/error.log
    CustomLog /var/www/my-crewlink.com/log/access.log combined
</VirtualHost>
</IfModule>
```

**Comment by Toys0125** [comment]
See the issue here is you using SSL which currently the game only support ws when they need to use wss for https.
Might add code to dectect https used in the url or ask the dev to add https support.
[connectionStuff.current.socket = io(`ws://${settings.serverIP}`, { transports: ['websocket'] });](https://github.com/ottomated/CrewLink/blob/8cec56e3988a47fa006d9b98b6c5066bf81518bc/src/renderer/Voice.tsx#L151)

**Comment by preciel** [comment]
> See the issue here is you using SSL which currently the game only support ws when they need to use wss for https.
> Might add code to dectect https used in the url or ask the dev to add https support.
> [connectionStuff.current.socket = io(`ws://${settings.serverIP}`, { transports: ['websocket'] });](https://github.com/ottomated/CrewLink/blob/8cec56e3988a47fa006d9b98b6c5066bf81518bc/src/renderer/Voice.tsx#L151)

So, I need to remove the SSL cert, and it will be good?

**Comment by Toys0125** [comment]
Well for the current build of the client I notice that someone is making a pull release to offer https support

**Comment by preciel** [comment]
I see, I will wait for it then.
I will keep using IP instead for now. :)

**Comment by Tandashi** [comment]
A reverse proxy with nginx worked for me. I am no apache expert but you might also need to rewrite the `/socket.io/` path.

Crewlink-server Version: `1.1.6`


Here is my working nginx config:

```
server {
  server_name crewlink.example.de;
  listen 443 ssl;

  include sites-available/ssl/ssl.conf;

  access_log /var/log/nginx/crewlink.example.de.log;
  error_log /var/log/nginx/crewlink.example.de_error.log;

  location / {
    proxy_pass http://127.0.0.1:9736;
    proxy_redirect off;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Url-Scheme $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
  }

  location /socket.io/ {
    proxy_pass http://127.0.0.1:9736;
    proxy_redirect off;

    proxy_http_version      1.1;

    proxy_set_header        Upgrade                 $http_upgrade;
    proxy_set_header        Connection              "upgrade";

    proxy_set_header        Host                    $host;
    proxy_set_header        X-Real-IP               $remote_addr;
    proxy_set_header        X-Forwarded-For         $proxy_add_x_forwarded_for;
  }
}
```

Hope this helps someone.

I am also using this `docker-compose.yml`:

```
version: "3"
services:
  crewlink:
    image: ottomated/crewlink-server:latest
    container_name: crewlink
    environment:
      - ADDRESS="https://crewlink.example.de"
    ports:
      - 9736:9736
```
