### ISSUE TITLE
Cannot define custom port to use (via direct yarn start command)

### ISSUE THREAD

**Issue by Shin-no-Ken** [ottomated/CrewLink-server#64]
I'm using a manual-run server (via "yarn start" command in powershell) and want to change the port that the server runs on. In the past, I've been manually editing index.ts and changing the port variable, but recently I implemented an auto-update section into my startup script, which resets index.ts back to its default state. Is there a way to define the port without editing index.ts?

I see what I think is a definition for a "PORT" environmental variable, but I have tried both adding "set PORT=(number)" to my script and adding a .env file to the root folder with the PORT variable defined within, and neither have worked. I have also tried both these methods with the new ADDRESS variable to no avail.

**Comment by Tandashi** [comment]
Did you try it like this: `PORT=7777 yarn start`?

That should be the shorthand for:
```bash
export PORT=7777
yarn start
```

**Comment by Shin-no-Ken** [comment]
From my reading online, that method only works in Linux; I am running the server on a Windows machine.
I tried both the shorthand and long forms anyway, and both returned CommandNotFoundExceptions.

**Comment by Shin-no-Ken** [comment]
After doing another deep dive for solutions, I finally found one [here](https://stackoverflow.com/questions/43024906/pass-node-js-environment-variable-with-windows-powershell) that does the trick on Windows. Instead of `PORT=(port) yarn start` as above, the correct code is `$env:PORT="(port)"; yarn start`.
