### ISSUE TITLE
Docker problem "exec format error" in log container

### ISSUE THREAD

**Issue by nEx-Ux1** [ottomated/CrewLink-server#74]
Hi,

I ran the docker line into my portainer.
The problem is the container never start. It try to start but after few second alive, it kill itself

There are some container log : 
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"

Thanks

**Comment by G-F-D** [comment]
The image on the Docker hub is only built for `amd64`, so if your machine uses a different architecture (eg. `arm`), it won't run. Build a Docker image on your machine for its architecture (see the [README](https://github.com/ottomated/CrewLink-server/blob/master/README.md#building-the-docker-image)).

**Comment by nEx-Ux1** [comment]
Thanks it works !
