### ISSUE TITLE
Problem connecting to local server

### ISSUE THREAD

**Issue by Nosfeltus** [ottomated/CrewLink-server#85]
I am using docker, trying to start a private vocal server.

However, I can not connect to my own server.
I did not find a previous link with this error, but I might have missed it....

I installed docker a minute ago, It seems to work.
I tried to run this command : docker run -d -p 9736:9736 ottomated/crewlink-server:latest

Here are the error and the proof that the server is running 

![temp](https://user-images.githubusercontent.com/76076937/102285089-cbcda280-3f35-11eb-804f-9243e0553030.PNG)

![temps 2](https://user-images.githubusercontent.com/76076937/102285405-8a89c280-3f36-11eb-8430-9fc3fb7b6272.PNG)

Edit : Here is the IP I tried to join with crewlink : localhost:9736

Sorry if this seems dumb, I'm kinda new to this
Does anyone know where the problem comes from?

**Comment by Tandashi** [comment]
Does it work when your use `http://localhost:9736`? It might be because you are missing the protocol information.

**Comment by Nosfeltus** [comment]
> 
> 
> Does it work when your use `http://localhost:9736`? It might be because you are missing the protocol information.

It appears to have solve my issue.
Thanks a lots for the help !
