### ISSUE TITLE
Among Us v12.3 Update

### ISSUE THREAD

**Issue by DispatchCommit** [ottomated/CrewLink-server#9]
Among Us just updated to a new version and there is not a corresponding yaml file on the server.

**Comment by DarkShoro** [comment]
They may be already doing it, please wait.

**Comment by swittenberger** [comment]
I don't know exactly what that yaml file contains/is generated. I don't think it is a hard fix to implement.

**Comment by DispatchCommit** [comment]
> They may be already doing it

Probably, but this issue can be used to track progress and prevents people from creating additional issues about the update.

> I don't know exactly what that yaml file contains/is generated.

I believe they are memory locations for various game state values. I'm not sure what the process is for finding the values though, but most likely is derived from some memory editor. If Ottomated is willing to share some insight there, it might allow for the community to help discover the relevant memory addresses for the offset file.

**Comment by Jeffmagma** [comment]
Yeah, it would be nice if some info on how offsets are found could be released so that the community could help with the update, but still the developer did a pretty good job with this client and I would be fine with waiting.

**Comment by DispatchCommit** [comment]
![image](https://user-images.githubusercontent.com/45262335/101213229-e72fd800-362e-11eb-8df1-412b302208c2.png)

Close, but not 100%

**Comment by SteefBew** [comment]
It doesn't crash for me but it says im in menu

**Comment by DispatchCommit** [comment]
https://github.com/ottomated/CrewLink-server/pull/11 has correct offsets for 12.3 😄 

Just waiting on merge & server update

**Comment by SteefBew** [comment]
So now whats the best way for those of us who installed the wrong offsets to clear the cached one, just delete %APPDATA%\
crewlink\config.json?

**Comment by DispatchCommit** [comment]
@SteefBew I had to edit the file to remove these lines, save, and then I did ctrl-r in crewlink to pull the new offsets from my server

![image](https://user-images.githubusercontent.com/45262335/101218154-66c1a500-3637-11eb-90ed-112e1b11e11a.png)

**Comment by SteefBew** [comment]
It looks like he's pushing a new version of the crewlink client with cacheing disabled, I see the version update on the git hub now  im guessing release is building
