### ISSUE TITLE
Can't connect to crewlink server behind reverse proxy

### ISSUE THREAD

**Issue by Cheos137** [ottomated/CrewLink-server#93]
I can't seem to be able to connect to my private crewlink server using crewlink.
(with my browser i can access the page of the crewlink server just fine)

I'm using an apache2 server as a reverse proxy (as i'm running multiple apps on my rootserver i cannot dedicate port 443 to just one of them). I'm starting the docker image with -p 9737:443 to expose the https port of the crewlink server container to another port than 443. By accessing my crewlink server (through the app) using https://crewlink.example.com:9737 it connects and does not show any problems.
In my apache config (virtual host config) i mapped port 443 for crewlink.cheos.dev to https://crewlink.example.com:9737. I tried using mod_proxy and mod_rewrite for this, both resulted in the same: the browser displays the webpage just fine, the crewlink app doesn't connect. (I also tried to use/not use mod_ssl on my apache server)

I seriously don't know what could be the issue here.

**Comment by Tandashi** [comment]
You probably also need to rewrite / proxypass the `/socket.io/` path to get it to work.

This is because crewlink uses [socket.io](https://socket.io) for their socket communication. 
I posted my nginx config in #6 since I am no apache expert. 
Maybe this helps you somehow.

**Comment by antipiot** [comment]
Experienced the same as reported there:
https://github.com/ottomated/CrewLink-server/issues/92

**Comment by Cheos137** [comment]
specially redirecting /socket.io/ sadly didn't help. (I can reach /socket.io/ with my browser even without an explicit redirect, too)

**Comment by GrayaMax** [comment]
Someone have a working Apache reverse proxy config to share ? i can't find the way to properly redirect socket.io. :(

**Comment by redstonedesigner** [comment]
Here's my (working as of 2021-01-25) Apache2 config: 

```
<VirtualHost crewlink.example.com:80>
  ServerName crewlink.example.com
RewriteEngine on
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
<IfModule mod_ssl.c>
<VirtualHost crewlink.example.com:443>
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:9736/
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://127.0.0.1:9736/$1" [P,L]
    ProxyPassReverse / http://127.0.0.1:9736/

    ServerName crewlink.example.com

SSLCertificateFile /etc/letsencrypt/live/crewlink.example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/crewlink.example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by Cheos137** [comment]
Thank you very much, this works like a charm!
